In [1]:
import numpy as np

In [2]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [5]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.66202948 0.18505308 0.40508732]
 [0.53686404 0.47635795 0.12506889]
 [0.73797083 0.21713821 0.96296478]]


In [6]:
# creating matrix with random integers
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[45  2 74 18 19]
 [31 42 42 94 49]
 [60  9 76 57 50]
 [27 95 18 62 71]]


In [7]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:

matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [9]:

null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[83 12 58 20 71]
 [ 4 97 17 83 51]
 [17 72 47 42 10]
 [44 71  1  2 65]]


In [11]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[83  4 17 44]
 [12 97 72 71]
 [58 17 47  1]
 [20 83 42  2]
 [71 51 10 65]]
